// Generated by gencpp from file robocon_msgs/chassis_msg.msg
// DO NOT EDIT!


#ifndef ROBOCON_MSGS_MESSAGE_CHASSIS_MSG_H
#define ROBOCON_MSGS_MESSAGE_CHASSIS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robocon_msgs
{
template <class ContainerAllocator>
struct chassis_msg_
{
  typedef chassis_msg_<ContainerAllocator> Type;

  chassis_msg_()
    : chassis()
    , str()  {
    }
  chassis_msg_(const ContainerAllocator& _alloc)
    : chassis(_alloc)
    , str(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _chassis_type;
  _chassis_type chassis;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;




  typedef boost::shared_ptr< ::robocon_msgs::chassis_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocon_msgs::chassis_msg_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_msg_

typedef ::robocon_msgs::chassis_msg_<std::allocator<void> > chassis_msg;

typedef boost::shared_ptr< ::robocon_msgs::chassis_msg > chassis_msgPtr;
typedef boost::shared_ptr< ::robocon_msgs::chassis_msg const> chassis_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocon_msgs::chassis_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocon_msgs::chassis_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robocon_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robocon_msgs': ['/home/yxiao1996/workspace/RoboTop/catkin_ws/src/Robocon/robocon_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocon_msgs::chassis_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocon_msgs::chassis_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocon_msgs::chassis_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a899e5eecd9f022d7c1366dd45f69c78";
  }

  static const char* value(const ::robocon_msgs::chassis_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa899e5eecd9f022dULL;
  static const uint64_t static_value2 = 0x7c1366dd45f69c78ULL;
};

template<class ContainerAllocator>
struct DataType< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocon_msgs/chassis_msg";
  }

  static const char* value(const ::robocon_msgs::chassis_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] chassis\n\
string str\n\
";
  }

  static const char* value(const ::robocon_msgs::chassis_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis);
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocon_msgs::chassis_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocon_msgs::chassis_msg_<ContainerAllocator>& v)
  {
    s << indent << "chassis[]" << std::endl;
    for (size_t i = 0; i < v.chassis.size(); ++i)
    {
      s << indent << "  chassis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.chassis[i]);
    }
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCON_MSGS_MESSAGE_CHASSIS_MSG_H
