// Generated by gencpp from file robocon_msgs/remoter_msg.msg
// DO NOT EDIT!


#ifndef ROBOCON_MSGS_MESSAGE_REMOTER_MSG_H
#define ROBOCON_MSGS_MESSAGE_REMOTER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robocon_msgs
{
template <class ContainerAllocator>
struct remoter_msg_
{
  typedef remoter_msg_<ContainerAllocator> Type;

  remoter_msg_()
    : position()
    , remote_data()
    , attitude()  {
    }
  remoter_msg_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , remote_data(_alloc)
    , attitude(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _remote_data_type;
  _remote_data_type remote_data;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _attitude_type;
  _attitude_type attitude;




  typedef boost::shared_ptr< ::robocon_msgs::remoter_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocon_msgs::remoter_msg_<ContainerAllocator> const> ConstPtr;

}; // struct remoter_msg_

typedef ::robocon_msgs::remoter_msg_<std::allocator<void> > remoter_msg;

typedef boost::shared_ptr< ::robocon_msgs::remoter_msg > remoter_msgPtr;
typedef boost::shared_ptr< ::robocon_msgs::remoter_msg const> remoter_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocon_msgs::remoter_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocon_msgs::remoter_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robocon_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robocon_msgs': ['/home/yxiao1996/workspace/RoboTop/catkin_ws/src/Robocon/robocon_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocon_msgs::remoter_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocon_msgs::remoter_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocon_msgs::remoter_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75585e5d82b120054891679ec4f80561";
  }

  static const char* value(const ::robocon_msgs::remoter_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75585e5d82b12005ULL;
  static const uint64_t static_value2 = 0x4891679ec4f80561ULL;
};

template<class ContainerAllocator>
struct DataType< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocon_msgs/remoter_msg";
  }

  static const char* value(const ::robocon_msgs::remoter_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] position\n\
float32[] remote_data\n\
float64[] attitude\n\
";
  }

  static const char* value(const ::robocon_msgs::remoter_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.remote_data);
      stream.next(m.attitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remoter_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocon_msgs::remoter_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocon_msgs::remoter_msg_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "remote_data[]" << std::endl;
    for (size_t i = 0; i < v.remote_data.size(); ++i)
    {
      s << indent << "  remote_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.remote_data[i]);
    }
    s << indent << "attitude[]" << std::endl;
    for (size_t i = 0; i < v.attitude.size(); ++i)
    {
      s << indent << "  attitude[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.attitude[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCON_MSGS_MESSAGE_REMOTER_MSG_H
