macro_tasks:
  macro_task_0:

  - move: sleep
    path:
    - [0.0, 0.0, 0.0]

  - move: sleep
    path:
    - [550.0, 6500.0, 90.0]

  - move: sleep
    path:
    - [6400.0, 6500.0, 90.0]

  - move: sleep
    path:
    - [3200.0, 6500.0, 90.0]

  - move: sleep
    path:
    - [550.0, 6500.0, -90.0]

  - move: sleep
    path:
    - [550.0, 4500.0, -90.0]

  - move: sleep
    path:
    - [3200.0, 4500.0, 90.0]

  - move: sleep
    path:
    - [550.0, 4500.0, -90.0]

  - move: sleep
    path:
    - [0.0, 0.0, 0.0]

  macro_task_1:
  - move: sleep
    path:
    - [500.0, 0.0, 0.0]
  - move: sleep
    path:
    - [0.0, 500.0, 0.0]
  - move: sleep
    path:
    - [500.0, 500.0, 0.0]
  - move: sleep
    path:
    - [0.0, 0.0, 0.0]
