protocol_auto:
   - "channel_0"
   - "channel_1"
   - "channel_2"
   - "channel_3"
   - "channel_4"
   - "channel_5"
   - "channel_6"
   - "channel_7"
   - "channel_8"
protocol_remote:
   - "channel_0"
   - "channel_1"
   - "channel_2"
   - "channel_3"
   - "button_0"
   - "button_1"
baudrate: 115200
update_frequency: 10
