# Initial state of the FSM
initial_state: "JOYSTICK_CONTROL"

events:
  joystick_override_on: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  reach_goal:
    topic: "odo_control_node/reach_goal"
    msg_type: "BoolStamped"
    trigger: True

global_transitions:
  joystick_override_on: "JOYSTICK_CONTROL"
  
nodes:
  detecter_node: "detector_node/switch"
  ccd_filter_node: "ccd_filter_node/switch"
  ccd_control_node: "ccd_control_node/switch"
  encoder_node_js: "serial_encoder_node/switch"
  pid_control_node: "pid_control_node/switch"
  odo_control_node: "odo_control_node/switch"

states:
  JOYSTICK_CONTROL:
    transitions:
      joystick_override_off: "LINE_FOLLOWING"
    active_nodes:
    - detecter_node
    - encoder_node_js
  LINE_FOLLOWING:
    transitions:
      reach_goal: "AT_GOAL"
    active_nodes:
    - ccd_filter_node
    - ccd_control_node
    - odo_control_node
  AT_GOAL:
    active_nodes:
    - pid_control_node