# Initial state of the FSM
initial_state: "JOYSTICK_CONTROL"

events:
  joystick_override_on: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True

  joystick_override_off: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False

  planning_complete:
    topic: "task_planner_node/confirm"
    msg_type: "BoolStamped"
    trigger: True

  reach_dest:
    topic: "path_planner_node/reach_dest"
    msg_type: "BoolStamped"
    trigger: True

  task_finish:
    topic: "task_planner_node/finish"
    msg_type: "BoolStamped"
    trigger: True

global_transitions:
  joystick_override_on: "JOYSTICK_CONTROL"
  
nodes:
  detecter_node: "detector_node/switch"
  ccd_filter_node: "ccd_filter_node/switch"
  ccd_control_node: "ccd_control_node/switch"
  encoder_node_js: "serial_encoder_node/switch"
  pid_control_node: "pid_control_node/switch"
  odo_control_node: "odo_control_node/switch"
  path_planner_node: "path_planner_node/switch"
  move_planner_node: "move_planner_node/switch"
  task_planner_node: "task_planner_node/switch"

states:
  JOYSTICK_CONTROL:
    transitions:
      joystick_override_off: "PLANNING"
    active_nodes:
    - detecter_node
    - encoder_node_js
  PLANNING:
    transitions:
      planning_complete: "LINE_FOLLOWING"
    active_nodes:
    - task_planner_node
    #- move_planner_node
    #- path_planner_node
  LINE_FOLLOWING:
    transitions:
      reach_dest: "AT_GOAL"
    active_nodes:
    - ccd_filter_node
    - ccd_control_node
    - odo_control_node
    - path_planner_node
  AT_GOAL:
    transitions:
      task_finish: "PLANNING"
    active_nodes:
    - pid_control_node
    - move_planner_node
